name: tg-bot-rasp

services:
  bot:
    network_mode: host
    environment:
      TZ: Europe/Moscow 
      BOT_TOKEN: ${BOT_TOKEN}
      ADMIN: ${ADMIN}
      MAIN_USER: ${MAIN_USER}
    build:
      context: .
    restart: unless-stopped
